name: MengPluginX
version: '${project.version}'
main: huanmeng.mengpluginx.MengPluginX
api-version: 1.16
softdepend:
  - PlaceholderAPI
commands:
  mpx_seed:
    description: Get the world seed
  online_player:
    description: Viewer server online players
  mpx_ping:
    description: Viewer the player ping
  mpx_tps:
    description: Viewer the server TPS
  mpx:
    description: Check if the plugin is started
  gm0:
    description: Set Player Game Mode Survival
  gm1:
    description: Set Player Game Mode Creative
  gm2:
    description: Set Player Game Mode Adventure
  gm3:
    description: Set Player Game Mode Spectator
permissions:
  mpx.huanmeng.op:
    description: Permission
    default: op
