name: MengPluginX
version: '${project.version}'
main: top.huanmeng.MengPluginX
api-version: 1.13
author: HuanMeng_
description: MengPluginX - A lightweight server management plugin
website: https://github.com/HuanMeng-official/MengPluginX/
softdepend:
  - PlaceholderAPI
commands:
  mpx_text:
    description: Spawn Holographic Text
  mpx_sa:
    description: Send Announcement
  mpx_uuid:
    description: Get Player UUID
  mpx_seed:
    description: Get the world seed
  online_player:
    description: Viewer server online players
  mpx_ping:
    description: Viewer the player ping
  mpx_tps:
    description: Viewer the server TPS
  mpx:
    description: Viewer the plugin basic information
  gm:
    description: Set Player Game Mode
permissions:
  mpx.huanmeng.op:
    description: Permission
    default: op