#Author: HuanMeng

#Bad word shielding switch
BadWords: true

#Default Reminder Person
Characters: '[HuanMeng]'
#Server name
#[HuanMeng]Player,welcome join the 'server'
Server: 'Server'
#Player join server tips
Tips: 'Tips'
#sleep tips
Sleep: 'Good evening'
#leave bed tips
Getup: 'Good morning'
#Player sends Bad-Worlds warning
Alert: 'Please pay attention to civilization'